### ISSUE TITLE
Add Composer support

### ISSUE THREAD

**Issue by GaryJones** [deckerweb/genesis-shortcode-ui#1]
Adding a `composer.json` would allow this plugin to be pulled into sites via composer.

**Comment by deckerweb** [comment]
Hi Gary!
Thanks for this good suggestion - I will add this soon!

**Comment by deckerweb** [comment]
I just added this file.
Hope that its content is correct that way, as I'm currently not using Composer myself...

**Comment by GaryJones** [comment]
Looks good!

Fixed in https://github.com/deckerweb/genesis-shortcode-ui/commit/a2320e7f568a8148e1514bdee7525da944025ccb.
